Feature/el03 riley
njoy/ACEtk pull request #13
Opened 2018-07-09 16:43 UTC by kbeling4

Included interface for Riley cross section data.

2018-07-13 19:13 UTC, david8dixon requested changes
Would be nice to resolve constexpr weirdness before merging. @apmccartney 

Why is the testing broken? @jlconlin

2018-07-13 19:13 UTC, david8dixon commented on src/ACEtk/interpretation/EL03/RileyCrossSection.hpp
> +  static constexpr int params_per_energy = 14;
Fails to link when using ```RileyCrossSection::params_per_energy``` rather than ```num_params```

2018-07-17 00:11 UTC, apmccartney approved these changes
Contingent on @david8dixon verifying format usage and the travis build passing. Good Work Kyle!

2018-07-17 00:11 UTC, apmccartney commented on src/ACEtk/interpretation/EL03/RileyCrossSection.hpp
> +    constexpr int num_params = 14;
Why is this repeated?

2018-07-17 00:11 UTC, apmccartney commented on src/ACEtk/interpretation/EL03/test/RileyCrossSections.test.cpp
> +      for ( const auto pair : ranges::view::zip ( reference2, el03.rileyCrossSection().values()[8] ) ) {
prefer `.front` to explicit indexing

2018-07-17 00:14 UTC, apmccartney commented
You have an uncommitted source file named `ACEtk/src/ACEtk/interpretation/EL03/RileyCrossSections.hpp` in your source tree. Please remove it and regenerate the Cmake files using metaconfigure

2018-07-17 00:27 UTC, apmccartney requested changes
Will approve when tests pass

2018-07-19 12:44 UTC, apmccartney approved these changes

2018-07-19 12:45 UTC, apmccartney commented
@david8dixon This is now waiting on your approval

2018-07-19 12:46 UTC, apmccartney commented
@kbeling4 You can see your test coverage results here: https://coveralls.io/builds/18045318/source?filename=src/ACEtk/interpretation/EL03/RileyCrossSection.hpp

2018-07-19 21:28 UTC, david8dixon approved these changes

2018-07-19 21:56 UTC, merged