Feature/positive
njoy/ACEtk pull request #17
Opened 2018-07-23 14:59 UTC by jlconlin

2018-07-24 16:56 UTC, jlconlin commented
This Pull Request is also ready. It will be much easier after the feature/Sorted Pull Request is finished.

2018-07-27 15:20 UTC, apmccartney requested changes
There are some come areas that require polish, but this is pretty solid work. Let's meet sometime today to discuss.

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/assignment.hpp
> +          utility::Require< true, std::is_constructible, Range, Arg > = true
What was the use case that lead you to verify assignable and constructible?

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/assignment.hpp
> +Positive& operator=( Arg arg ){
Argument taken by value. Please take by forwarding reference.

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/assignment.hpp
> +          utility::Require< false, std::is_assignable, Range&, Arg > = true
Here you require that the argument is not assignable to the range and then attempt to assign to it

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/check.hpp
> +          utility::Require< true, utility::is_range, Range > = true >
Redundant requirement. `Sorted -> true` implies `range -> true`

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/ctor.hpp
> +Positive( Sorted< Arg >&& arg ) :
The `Sorted` template here is pessimizing. You've enforced this with a requirement.

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/ctor.hpp
> +Positive( Sorted< Arg >&& arg ) :
In fact this can removed all together. You're check function has the appropriate logic to handle the sorted case.

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/ctor.hpp
> +template< typename Arg = std::initializer_list< typename Range::value_type >,
nested value_type typedef not necessarily provided

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/StrictlyPositive/src/assignment.hpp
> +          utility::Require< true, std::is_constructible, Range, Arg > = true
please remove is constructible requirement

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/StrictlyPositive/src/assignment.hpp
> +StrictlyPositive& operator=( Arg arg ){
please take argument by forwarding ref

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/check.hpp
> +}
Please add a check that requires strictly positive and simply returns the argument

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/Positive/src/check.hpp
> +}
By adding a check that requires positive, the logic for the ctors and assignment can be simplified

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/StrictlyPositive/src/check.hpp
> +          utility::Require< true, utility::is_range, Range > = true >
`sorted -> true`  implies `range -> true`

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/StrictlyPositive/src/check.hpp
> +  if( *( arg.begin() ) < 0.0 ){
`<` to `<=`

2018-07-27 15:20 UTC, apmccartney commented on src/ACEtk/details/verify/StrictlyPositive/src/ctor.hpp
> +          utility::Require< true, utility::is_range, Arg > = true,
`sorted -> true` implies `range -> true`

2018-07-29 00:12 UTC, apmccartney approved these changes

2018-07-29 00:12 UTC, merged