AND block components
njoy/ACEtk pull request #42
Opened 2021-10-14 21:28 UTC by whaeck

This implements the following AND block components:
- tabulated angular distirbution for a single incident energy
- 32 equiprobable bins for a single incident energy
- isotropic distirbution for a single incident energy
- angular distribution data for a single reaction

This also adds an enum for the angular distribution type.

The AND block is next.

2021-10-22 20:47 UTC, nathangibson14 requested changes
One question and one bad piece of documentation.  Everything else looks good.

2021-10-22 20:47 UTC, nathangibson14 commented on src/ACEtk/block/AngularDistributionData/src/ctor.hpp
> + *  @param[in] lsig    the begin iterator of the LSIG block in the XSS array
Documentation doesn't apply to this constructor.

2021-10-22 20:47 UTC, nathangibson14 commented on src/utility/overload.hpp
> +#define NJOY_UTILITY_OVERLOAD
This looks like something taken from another component.  Is this C&P from elsewhere or new?  Does it belong in ACEtk rather than a dependency?

2021-10-25 17:02 UTC, whaeck commented on src/ACEtk/block/AngularDistributionData/src/ctor.hpp
> + *  @param[in] lsig    the begin iterator of the LSIG block in the XSS array
Gotta hate copy/paste ...
Should be fixed now.

2021-10-25 17:05 UTC, whaeck commented on src/utility/overload.hpp
> +#define NJOY_UTILITY_OVERLOAD
Eventually it should go into a dependency, yes (which is why I already put it separately from ACEtk). When we overhaul header-utilities we might add it to that. It's essentially a very simple piece of template code.

2021-10-29 15:22 UTC, nathangibson14 approved these changes

2021-10-29 15:22 UTC, merged